baseURL: http://deployemproducao.dev
languageCode: pt-br
title: Em breve Deploy em Produção para desenvolvedores
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: 
  navbarlogo:
  # Logo (from static/images/logos/___)
    #image: logos/fresh.svg
    image: logos/deploy.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Deploy em produção para desenvolvedores
    # Hero subtitle (optional)
    subtitle: Um livro aberto e completamente livre
    # Button text
    buttontext: Em breve
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    #image: illustrations/worker.svg
    image: illustrations/deploy.jpeg
    # Footer logos (from static/images/logos/clients/___.svg)
    #clientlogos:
    #- systek
    #- tribe
    #- kromo
    #- infinite
    #- gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Sobre
    url: /sobre
  - title: Licença
    url: https://creativecommons.org/licenses/by/4.0/
  - title: Colaboração
    sublinks:
    - title: Como está sendo construído
      url: /construido
    - title: Como colaborar
      url: /como-colaborar
    - title: Quem já colaborou
      url: /quem-colaborou
  #- title: Log in
  #  url: /
  #- title: Sign up
  #  url: /
  #  button: true
  section1:
    title: Qual a ideia do livro?
    subtitle: Como ele será dividido
    tiles:
    - title: Fundamentos
      icon: mouse-globe
      text: Conceitos que você precisa saber antes de começar
      url: /
      buttonText: Em breve
    - title: Como ir para produção
      icon: laptop-cloud
      text: Casos reais de como colocar em produção aquele projeto
      url: /
      buttonText: Em breve
    - title: Deploy do deploy
      icon: plug-cloud
      text: O que fazer depois de chegar em produção
      url: /
      buttonText: Em breve
  section2:
    title: O que esse livro tem de diferente
    subtitle: Porque colaborar com ele?
    features:
    - title: Conhecimento aberto
      text: Esse livro é completamente aberto. Você pode baixar, modificar, distribuir e fazer uso com fins financeiros sem consultar ninguém! Basta citar a origem.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: doc-sync
    - title: Colaborativo
      text: Esse livro é a soma de um esforço comunitário, ou seja, é a obra de várias mãos. Um trabalho feito por uma comunidade vibrante e dedicada para manter o conhecimento como ele é, por origem aberto!
      icon: laptop-globe
    - title: DRM Free
      text: Somos contra a qualquer tipo de controle da informação, ou seja, esse livro NUNCA será distribuído sob DRM ou qualquer mecanismo parecido.
      icon: mobile-feed
  #section3:
  #  title: One platform
  #  subtitle: To rule them all
  #  image: illustrations/mockups/app-mockup.png
  #  buttonText: Get started
  #  buttonLink: "#"
  #section4:
  #  title: Our Clients love us!
  #  subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #  clients:
  #  - name: Irma Walters
  #    quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis #scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #    job: Accountant
  #    img: 1
  #  - name: John Bradley
  #    quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis #scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #    job: Financial Analyst
  #    img: 2
  #  - name: Gary Blackman
  #    quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis #scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #    job: HR Manager
  #    img: 3
  #section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: gnu.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: #
      # Icons are from Font Awesome
      icon: github
    - link: https://twitter.com/deployemprod
      icon: twitter
    bulmalogo: false
    quicklinks:
      column1:
        title: "Editora?"
        links:
        - text: Leanpub
          link: /
      column2:
        title: "Docs"
        links:
        - text: Perguntas frequentes
          link: /
        - text: Guia do colaborador
          link: /
      column3:
        title: "Blog"
        links:
        - text: Gomex
          link: https://gomex.me
